 -- Exercício 1
 
 create view vwAutor
 as select TB_AUTOR.COD_AUT as 'Codigo', 
		   TB_AUTOR.NOME_AUT as 'Nome'
	from TB_AUTOR;

	select * from vwAutor;	
	
-- Exercício 2
	create view vwsla
	as SELECT	TB_AUTOR.COD_AUT AS 'CODIGO',
        TB_AUTOR.NOME_AUT AS 'NOME AUTOR',
		TB_LIVRO.COD_LIV AS 'COD',
		TB_LIVRO.TITULO_LIV AS 'TITULO',
		TB_LIVRO.PRECO_LIV AS 'PREÇO',
		TB_EDITORA.NOME_ED AS 'EDITORA'
FROM TB_AUTOR INNER JOIN TB_AUTO_LIVRO
  ON TB_AUTOR.COD_AUT = TB_AUTO_LIVRO.COD_AUT INNER  JOIN TB_LIVRO 
  ON TB_LIVRO.COD_LIV = TB_AUTO_LIVRO.COD_LIV INNER  JOIN TB_ED_LIV 
  ON TB_LIVRO.COD_LIV = TB_ED_LIV.COD_LIV INNER  JOIN TB_EDITORA 
  ON TB_EDITORA.COD_ED = TB_ED_LIV.COD_ED;
 --ORDER BY TB_AUTOR.NOME_AUT;

 select * from vwsla;


